### PR TITLE
Bump Sholl_Analysis to latest release (3.4.5)

### PR DESCRIPTION
**Pull request by tferr**

### CODE REVIEW

**Comment by ctrueden** [comment]
Cool.

**Comment by tferr** [comment]
Thanks!

**Comment by tferr** [comment]
Hi @ctrueden,

The Fiji updater seems to be unaware of the new version. I still get previous version (3.4.4) on a fresh Fiji installation. Did I forget something?

**Comment by ctrueden** [comment]
Firstly, we did not cut a new release of `pom-fiji` yet. Secondly, the [fiji/fiji](https://github.com/fiji/fiji) project was not updated to use such a new release of pom-fiji. Thirdly, even if we did those first two steps, we still do not have Jenkins hooked up to `fiji/fiji` to automatically upload the status of the master branch to the Fiji update site.

Basically, the update sites are still completely disconnected from what's in Git. So the desired JAR file(s) must be uploaded manually. Further reading on the [Releases page](http://imagej.net/Releases#Phases_of_development).

Anyway, no worries. I uploaded it for you now. :beers:

**Comment by tferr** [comment]
Thanks! I got all confused with this discussion from previous release:  [#111](https://github.com/fiji/fiji/issues/111).

Thanks for the info. So, what would be more efficient from your side for next release:
- That I get a Jenkins account?
- Or that I ask you to upload the new version via PRs?

**Comment by ctrueden** [comment]
The Fiji release process is not ideal yet.

Ultimately, the workflow we _want_ to have is:

* Update `pom-fiji` to the desired new version number
* Cut a new `pom-fiji` release
* Update `fiji` to use the new `pom-fiji` release
* And Jenkins takes care of uploading new stuff to the Fiji update site

But we are still a ways off from that. One current workflow is:

* File a PR in `pom-fiji` with the desired new version number, as you did
* Comment on the PR stating that you wish for this version to be uploaded to Fiji
* Wait for a Fiji maintainer to upload your release

What some Fiji developers do right now is to simply upload their new release, without updating `pom-fiji` or `fiji` at all. And then @hinerm and I end up playing "catch-up" and updating the `pom-fiji` etc. to reflect those new releases which were already uploaded. This results in "source code skew" where someone building `fiji/fiji` from source gets different artifacts than what's on the update site.

The reason I didn't upload your new `Sholl_Analysis` this time was simply time—you didn't specifically request it and so I was just waiting till enough new releases accumulated on http://status.imagej.net/ so we could do them all at once. This happens maybe 1/month on average.

I could certainly grant your ImageJ wiki account upload rights to the Fiji update site, at which point you could upload `Sholl_Analysis` yourself whenever you want for instant gratification. If you anticipate lots of new releases in coming weeks and months, maybe that would be the best route for the near future.

**Comment by tferr** [comment]
Thanks for the clear explanation.
The current workflow you describe seems effective as is for this plugin. Just checked the frequency of releases: It has been roughly 1 every 3 months for the last year and half. I do not foresee any changes to this, unless someone else wants to help.
I'll just be more explicit next time if I think the upload should be fast-tracked (IJ.49t [broke some of the plugin's plots](https://github.com/tferr/ASA/blob/master/Notes.md#version-345-june-2015), hence my insistence with this release).
Thanks once more, really appreciated. Hopefully I can make it to this fall's [conference](http://imagej.net/Conference_2015) to learn more about IJ development!

**Comment by ctrueden** [comment]
> Thanks once more, really appreciated.

You're very welcome. Thanks to you as well—the ImageJ community owes you a big debt for all your efforts!

> I'll just be more explicit next time if I think the upload should be fast-tracked

Sounds good.

> Hopefully I can make it to this fall's conference to learn more about IJ development!

That would be fantastic!

**Pull request merged**
