### PR TITLE
release 9.0.0

### PR DESCRIPTION
**Pull request by axtimwalde**
upgraded dependencies:

mpicbg-1.0.1
mpicbg_1.0.1
legacy-imglib1-1.1.3-DEPRECATED
panorama_-3.0.0
Stitching_-3.0.1

added dependencies:

FS_Align_TrakEM2-2.0.1
Reconstruct_Reader-2.0.2
TrakEM2_Archipelago-2.0.1
blockmatching_-2.1.1
register_virtual_stack_slices-2.0.3
mpicbg-trakem2-1.2.2
TrakEM2_-1.0f
jitk-tps-1.1.1
trakem2_tps-1.1.1

to be released with:

SPIM_Registration-2.1.6
Descriptor_based_registration-2.0.10,
bigdataviewer-core-1.0.8
spimdata-1.0.0-beta-5
pom-bigdataviewer-1.1.2

...and whatever else depends on that

### CODE REVIEW

**Comment by axtimwalde** [comment]
@tpietzsch @ctrueden @StephanPreibisch:
SPIM_Registration depends on both bigdataviewer and mpicbg, i.e. bigdataviewer and dependencies have to be updated in parallel to this upgrade.  Could you please have a look at the versions above and trigger an update when this pull-request is accepted?

**Comment by ctrueden** [comment]
See also https://github.com/fiji/fiji/issues/113, which this PR seeks to address.

**Comment by hinerm** [comment]
@tpietzsch @StephanPreibisch @ctrueden 
Note that, [as discussed here](https://github.com/fiji/panorama/commit/261dfb280e11cd0ca9d1a63eb2b93f0c3bd33638#commitcomment-10439153), `pom-trakem2 1.3.2` was released multiple times and thus did not deploy to our maven repo, so if you try to consume it you will not get the current desired dependency state.
My recommendation is to go to `1.3.3` and consume this instead.

**Comment by tpietzsch** [comment]
@axtimwalde @StephanPreibisch @ctrueden @hinerm
By update you mean "upload to the Fiji update site"? Is there anything else you need me to do?

Once there is the pom-fiji 9.0.0 I will update pom-bigdataviewer to use 9.0.0 as parent, and update bigdataviewer-core/_fiji/-server to use use that new pom-bigdataviewer. I don't think it is critical to do this in parallel to the deployment of the new mpicbg to the Fiji updater: None of the bdv projects consumes mpicbg directly. bdv_fiji consumes it indirectly via SPIM_Registration. I just verified that bdv_fiji compiles with SPIM_Registration-2.1.7 (modulo enforcer rules) so I expect no jar incompatibilities.

Am I getting the overall picture right, or is there something I missed?

**Comment by StephanPreibisch** [comment]
But the upload through the Fiji updater has to be done in parallel, the current Spimregistration will break with the new mpicbg, vice versa will the new Spimregistration not work with the old mpicbg. At the same time the new Spimregistration does not work with the current version of the BDV (just talking about jars in the Fiji uploader). Cheers, Steffi

**Comment by axtimwalde** [comment]
mpicbg-1.0.1
mpicbg_1.0.1
legacy-imglib1-1.1.3-DEPRECATED
panorama_-3.0.0
Stitching_-3.0.1

added dependencies:

FS_Align_TrakEM2-2.0.1
Reconstruct_Reader-2.0.2
TrakEM2_Archipelago-2.0.1
blockmatching_-2.1.1
register_virtual_stack_slices-2.0.3
mpicbg-trakem2-1.2.2
TrakEM2_-1.0f
jitk-tps-1.1.1
trakem2_tps-1.1.1

to be released with:

SPIM_Registration-2.1.7
Descriptor_based_registration-2.0.11,
bigdataviewer-core-1.0.8
spimdata-1.0.0-beta-5
pom-bigdataviewer-1.1.2

**Comment by axtimwalde** [comment]
This pull-request is ready for merge as pom-trakem2-1.3.3 is available.

**Pull request merged**
