### PR TITLE
Moving H5J_Loader_Plugin to version 1.0.4

### PR DESCRIPTION
**Pull request by lesfoster**
This latest pull request silences all log output from the plugin.

### CODE REVIEW

**Comment by ctrueden** [comment]
:+1:

**Comment by lesfoster** [comment]
Curtis, et al:
How is this progressing?  My latest Fiji update did not get me the latest plugin.
Regards,
Les

**Comment by ctrueden** [comment]
I will cut releases for you now.

**Comment by ctrueden** [comment]
OK, I uploaded the new `H5J_Loader_Plugin`.

**Pull request merged**
